# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "dckppn01"
  config.vm.network "public_network", bridge: "wlp1s0"
  config.vm.synced_folder "data/", "/data/",mount_options: ["dmode=777","fmode=777"], create: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
  end
  config.vm.provision "shell", path: "setup.sh"
end
